[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "patroni /etc/patroni/patroni.yml"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "always"
restartPolicyMaxRetries = 10
numReplicas = 1
